resolver: lts-13.9
packages:
- '.'
- location:
   git:    https://github.com/haskell-numerics/hmatrix.git 
   commit: c4b80ef9951b533d6bbbb34df8109f3290546296
  subdirs:
  - "packages/base"
extra-deps: []
