resolver: lts-3.11
packages:
- '.'
- location:
   git:    https://github.com/obadz/hmatrix.git 
   commit: db5fe25c28e6a67eed9fbc65412110480086641b
  subdirs:
  - "packages/base"
extra-deps: []
flags:
  hmatrix:
    openblas: true
