resolver: lts-3.11
packages:
- '.'
- location:
   git:    https://github.com/albertoruiz/hmatrix.git 
   commit: ebf8ce6595c6d11bcc3662e84a32822c2eaaa77a
  subdirs:
  - "packages/base"
extra-deps: []
flags: {}

