resolver: lts-5.4
packages:
- '.'
- location:
   git:    https://github.com/marcinmrotek/hmatrix.git 
   commit: 283fc116b73a3199edeaf13e1cc7b59b150a964d
  subdirs:
  - "packages/base"
extra-deps: []
flags:
  hmatrix:
    openblas: true
